export const PORTAL_CONFIGS = {
  restaurant: {
    portalName: 'Food License',
    portalAccent: 'Portal',
    titleHindi: 'खाद्य सुरक्षा रजिस्ट्रेशन लाइसेंस के प्राइवेट विशेषज्ञों का पोर्टल',
    titleEnglish: 'FOOD SAFETY REGISTRATION LICENSE PRIVATE CONSULTANT PORTAL',
    slogan: 'SAFE FOOD · BETTER HEALTH',
    emblemLabel: 'FSSAI',
    colors: { navy: '#0a1a2a', orange: '#e6a756', green: '#38761d', accent: '#1e3a5f' },
    ticker:
      'Food License is mandatory for all food businesses in India. Apply for renewal before expiry to avoid penalties. | FSSAI registration ensures safe food for every citizen.',
    heroImage: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=1400&q=80',
    heroCaption: 'Ensuring food safety standards across India',
    galleryImages: [
      { src: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=600&q=80', alt: 'Restaurant kitchen inspection' },
      { src: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=600&q=80', alt: 'Fresh food preparation' },
      { src: 'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=600&q=80', alt: 'Food service compliance' },
    ],
    idField: { label: 'FSSAI No', name: 'fssai_number', placeholder: 'FSSAI No' },
    idLabel: 'FSSAI No',
    addressHint: 'Complete operating address of the food business.',
    footer: 'Restaurant & Food Service · FSSAI Food License · Government of India Initiative',
    department: 'Ministry of Health & Family Welfare',
  },
  education: {
    portalName: 'Education License',
    portalAccent: 'Portal',
    titleHindi: 'शिक्षा संस्थान पंजीकरण एवं नवीनीकरण लाइसेंस पोर्टल',
    titleEnglish: 'SHOP & ESTABLISHMENT REGISTRATION LICENSE PORTAL FOR EDUCATIONAL INSTITUTIONS',
    slogan: 'QUALITY EDUCATION · BRIGHT FUTURE',
    emblemLabel: 'MoE',
    colors: { navy: '#1a365d', orange: '#dd6b20', green: '#2f855a', accent: '#2b6cb0' },
    ticker:
      'All educational institutions must hold a valid Shop & Establishment license. Renew on time to continue operations legally. | Directorate of Education compliance required.',
    heroImage: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?w=1400&q=80',
    heroCaption: 'Regulating educational institutions for quality learning',
    galleryImages: [
      { src: 'https://images.unsplash.com/photo-1498243691581-b145c3f54a5a?w=600&q=80', alt: 'University campus' },
      { src: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?w=600&q=80', alt: 'Classroom learning' },
      { src: 'https://images.unsplash.com/photo-1503676260728-1c00da094a0b?w=600&q=80', alt: 'School building' },
    ],
    idField: { label: 'Establishment Reg. No.', name: 'license_no', placeholder: 'Establishment Reg. No.' },
    idLabel: 'Establishment Reg. No.',
    addressHint: 'Complete institution address.',
    footer: 'Education & Institution · Shop & Establishment License',
    department: 'Ministry of Education',
  },
  hospital: {
    portalName: 'Health Facility',
    portalAccent: 'Portal',
    titleHindi: 'स्वास्थ्य सुविधा लाइसेंस पंजीकरण एवं नवीनीकरण पोर्टल',
    titleEnglish: 'HEALTH FACILITY LICENSE REGISTRATION & RENEWAL PORTAL',
    slogan: 'SAFE CARE · HEALTHY NATION',
    emblemLabel: 'MoHFW',
    colors: { navy: '#0d3b2e', orange: '#c05621', green: '#276749', accent: '#2f855a' },
    ticker:
      'All hospitals and clinics must renew health facility licenses annually. Non-compliance may lead to closure. | National Health Mission guidelines apply.',
    heroImage: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=1400&q=80',
    heroCaption: 'Licensed healthcare for every citizen',
    galleryImages: [
      { src: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=600&q=80', alt: 'Hospital ward' },
      { src: 'https://images.unsplash.com/photo-1631217868264-e5b1bb5e2abb?w=600&q=80', alt: 'Medical professionals' },
      { src: 'https://images.unsplash.com/photo-1586773860418-d37222d8fce3?w=600&q=80', alt: 'Healthcare facility' },
    ],
    idField: { label: 'License / NOC No.', name: 'license_no', placeholder: 'License / NOC No.' },
    idLabel: 'License / NOC No.',
    addressHint: 'Complete facility address.',
    footer: 'Hospital & Healthcare · Health Facility License',
    department: 'Ministry of Health & Family Welfare',
  },
  hotel: {
    portalName: 'Hotel License',
    portalAccent: 'Portal',
    titleHindi: 'होटल एवं आतिथ्य व्यवसाय ट्रेड लाइसेंस पोर्टल',
    titleEnglish: 'HOTEL & HOSPITALITY TRADE LICENSE REGISTRATION PORTAL',
    slogan: 'HOSPITALITY · TOURISM · GROWTH',
    emblemLabel: 'MoT',
    colors: { navy: '#1a202c', orange: '#b7791f', green: '#2d6a4f', accent: '#744210' },
    ticker:
      'Hotels and lodging establishments must hold a valid trade license. Renew before expiry to continue guest services. | Tourism department regulations apply.',
    heroImage: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=1400&q=80',
    heroCaption: 'Promoting safe and licensed hospitality services',
    galleryImages: [
      { src: 'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?w=600&q=80', alt: 'Hotel lobby' },
      { src: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?w=600&q=80', alt: 'Hotel room' },
      { src: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=600&q=80', alt: 'Resort hospitality' },
    ],
    idField: { label: 'Trade License No.', name: 'trade_license_number', placeholder: 'Trade License No.' },
    idLabel: 'Trade License No.',
    addressHint: 'Complete hotel/premises address.',
    footer: 'Hotel & Hospitality · Trade License',
    department: 'Ministry of Tourism',
  },
  manufacturing: {
    portalName: 'Industrial License',
    portalAccent: 'Portal',
    titleHindi: 'विनिर्माण एवं औद्योगिक इकाई पंजीकरण पोर्टल',
    titleEnglish: 'MANUFACTURING & INDUSTRIAL UNIT GST REGISTRATION PORTAL',
    slogan: 'MAKE IN INDIA · COMPLIANT INDUSTRY',
    emblemLabel: 'DPIIT',
    colors: { navy: '#1a202c', orange: '#d69e2e', green: '#22543d', accent: '#2d3748' },
    ticker:
      'All manufacturing units must maintain valid GST registration. File renewal applications before due date. | MSME and industrial compliance norms apply.',
    heroImage: 'https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=1400&q=80',
    heroCaption: 'Licensed manufacturing for economic growth',
    galleryImages: [
      { src: 'https://images.unsplash.com/photo-1565043589221-1a6fd9a4d2f7?w=600&q=80', alt: 'Factory floor' },
      { src: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=600&q=80', alt: 'Industrial plant' },
      { src: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?w=600&q=80', alt: 'Manufacturing equipment' },
    ],
    idField: { label: 'GSTIN', name: 'gstin', placeholder: 'GSTIN' },
    idLabel: 'GSTIN',
    addressHint: 'Complete factory/operating address.',
    footer: 'Manufacturing & Industrial · GST Registration',
    department: 'Ministry of Commerce & Industry',
  },
  pharmacy: {
    portalName: 'Drug License',
    portalAccent: 'Portal',
    titleHindi: 'औषधि लाइसेंस पंजीकरण एवं नवीनीकरण पोर्टल',
    titleEnglish: 'PHARMACY & DRUG CONTROL LICENSE REGISTRATION PORTAL',
    slogan: 'SAFE MEDICINES · PUBLIC HEALTH',
    emblemLabel: 'CDSCO',
    colors: { navy: '#0b2447', orange: '#c05621', green: '#276749', accent: '#19376d' },
    ticker:
      'All pharmacies must hold a valid drug license under the Drugs & Cosmetics Act. Renewal is mandatory every year. | State Drug Control authority oversight.',
    heroImage: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=1400&q=80',
    heroCaption: 'Regulated medicines for public safety',
    galleryImages: [
      { src: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80', alt: 'Pharmacy counter' },
      { src: 'https://images.unsplash.com/photo-1631549916768-4119b2d7a7a1?w=600&q=80', alt: 'Medicine storage' },
      { src: 'https://images.unsplash.com/photo-1587854692152-cf800b29b369?w=600&q=80', alt: 'Licensed pharmacist' },
    ],
    idField: { label: 'Drug License No.', name: 'license_no', placeholder: 'Drug License No.' },
    idLabel: 'Drug License No.',
    addressHint: 'Complete pharmacy address.',
    footer: 'Pharmacy & Drug Control · Drug License',
    department: 'Ministry of Health & Family Welfare',
  },
};
